ci:
    autoupdate_schedule: monthly
    skip:
    - prettier
    - eslint
    - stylelint
default_language_version:
    node: system
repos:
  - repo: https://github.com/ComPWA/mirrors-taplo
    rev: 'v0.8.1'
    hooks:
    -   id: taplo
  - repo: local
    hooks:
      - id: ruff-format-hatch-settings
        name: hatch-ruff
        language: system
        entry: hatch fmt
        pass_filenames: false
        verbose: true
