ci:
    autoupdate_schedule: monthly
    skip:
    - prettier
    - eslint
    - stylelint
default_language_version:
    node: system
repos:
  - repo: https://github.com/ComPWA/mirrors-taplo
    rev: 'v0.8.1'
    hooks:
    -   id: taplo
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format