name: ipylab-lite
channels:
  - conda-forge
dependencies:
  - python=3.11
  - mamba
  - pydata-sphinx-theme
  - myst-parser
  - build
  - ipywidgets >=8.1,<9
  - jupyterlab >=4.1,<5
  - jupyterlite-core
  - jupyterlite-pyodide-kernel
  - jupyterlite-sphinx
  - nodejs=20
  - pip:
      - ..
