name: Packaging

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1

defaults:
  run:
    shell: bash -e {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - name: Install dependencies
        run: |
          pip install .[dev]
      - name: Build pypi distributions
        run: |
          hatch build
      - name: Build npm distributions
        run: |
          npm pack
          cp *.tgz dist
      - name: Build checksum file
        run: |
          cd dist
          sha256sum * | tee SHA256SUMS
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: dist ${{ github.run_number }}
          path: ./dist

  install:
    runs-on: ${{ matrix.os }}-latest
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python: ['3.11', '3.12']
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: 'x64'
      - uses: actions/download-artifact@v4
        with:
          name: dist ${{ github.run_number }}
          path: ./dist
      - name: Install the package
        run: |
          cd dist
          pip install ipylab*.whl
      - name: Validate environment
        run: |
          pip freeze
          pip check
      - name: Validate the install
        run: |
          jupyter labextension list
          jupyter labextension list 2>&1 | grep -ie "ipylab.*enabled.*ok" -
